import './globals.css'
import type { Metadata } from 'next'
import {Inter, Lexend} from 'next/font/google'
import {Providers} from '../components/providers';

const inter = Inter({ subsets: ['latin'] })
const lexend = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Providers font={lexend}>
            <body className={inter.className}>
                {children}
            </body>
        </Providers>
    </html>
  )
}
